version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network

  discovery-server:
    image: caszarjos/discovery-server
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      - eureka.instance.hostname=discovery-server

  api-gateway:
    image: caszarjos/api-gateway
    build:
      context: ./api-gateway-eureka
    container_name: api-gateway
    ports:
      - "8000:8000"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.application.name=api-gateway
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
      - logging.level.root=INFO
      - logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
      - logging.level.org.springframework.cloud.gateway=TRACE

  trends-service:
    image: caszarjos/trends-service
    build:
      context: ./trends
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://34.122.45.182:3306/green-grow-db?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=%aO|cS{Z(&doRJx#
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  posts-service:
    image: caszarjos/posts-service
    build:
      context: ./posts
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://34.122.45.182:3306/green-grow-db?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=%aO|cS{Z(&doRJx#
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  articles-service:
    image: caszarjos/articles-service
    build:
      context: ./articles
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://34.122.45.182:3306/green-grow-db?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=%aO|cS{Z(&doRJx#
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  courses-service:
    image: caszarjos/courses-service
    build:
      context: ./courses
    networks:
      - microservices-network
    depends_on:
      - discovery-server
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.application.name=courses-service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  profiles-service:
    image: caszarjos/profiles-service
    build:
      context: ./profiles
    networks:
      - microservices-network
    depends_on:
      - discovery-server
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.application.name=profiles-service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

networks:
  microservices-network:
    driver: bridge