version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      - eureka.instance.hostname=discovery-server

  api-gateway:
    build:
      context: ./api-gateway-eureka
    container_name: api-gateway
    ports:
      - "8000:8000"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.application.name=api-gateway
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
      - logging.level.root=INFO
      - logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
      - logging.level.org.springframework.cloud.gateway=TRACE

  trends-service:
    build:
      context: ./trends
    container_name: trends-service
    ports:
      - "8084:8084"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://34.122.45.182:3306/green-grow-db?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=%aO|cS{Z(&doRJx#
      - spring.jpa.hibernate.ddl-auto=update
      - server.port=8084
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  posts-service:
    build:
      context: ./posts
    container_name: posts-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://34.122.45.182:3306/green-grow-db?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=%aO|cS{Z(&doRJx#
      - spring.jpa.hibernate.ddl-auto=update
      - server.port=8082
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  articles-service:
    build:
      context: ./articles
    container_name: articles-service
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://34.122.45.182:3306/green-grow-db?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=%aO|cS{Z(&doRJx#
      - spring.jpa.hibernate.ddl-auto=update
      - server.port=8080
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  courses-service:
    build:
      context: ./courses
    container_name: courses-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.application.name=courses-service
      - server.port=8081
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

  profiles-service:
    build:
      context: ./profiles
    container_name: profiles-service
    ports:
      - "8083:8083"
    networks:
      - microservices-network
    depends_on:
      - discovery-server
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.application.name=profiles-service
      - server.port=8083
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

networks:
  microservices-network:
    driver: bridge